FROM python:3.9.14-slim-bullseye

# set work directory
WORKDIR /cubode_agent

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install Packages
RUN apt-get -y update && apt-get -y install nano

# Install Requirements
COPY ./docker/requirements.txt .
RUN pip install -r requirements.txt
